# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - "CODEOWNERS"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.adoc"
      - "dco.txt"
      - "LICENSE"
      - "README.md"
      - "SECURITY.md"
      - "*/README.adoc"
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK's
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: |
              11
              17
              21
              25
      - name: Build with Maven - ${{ matrix.os }}
        run:  |
          mvn clean install -U -B -fae '-Djava11.home=${{env.JAVA_HOME_11_X64}}' '-Djava17.home=${{env.JAVA_HOME_17_X64}}' '-Djava21.home=${{env.JAVA_HOME_21_X64}}'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}
          path: '**/surefire-reports/'
  legacy-test:
      runs-on: ubuntu-latest
      timeout-minutes: 90

      steps:
          - uses: actions/checkout@v5
          - name: Set up JDK's
            uses: actions/setup-java@v5
            with:
                distribution: 'temurin'
                cache: 'maven'
                java-version: |
                    11
                    17
                    21
                    25
          - name: Legacy Test
            run:  |
                mvn clean install -U -B
                mvn test -Dlegacy.test -Djava11.home=${{env.JAVA_HOME_11_X64}} -Djava17.home=${{env.JAVA_HOME_17_X64}} -Djava21.home=${{env.JAVA_HOME_21_X64}}
          - uses: actions/upload-artifact@v5
            if: failure()
            with:
                name: legacy-surefire-reports
                path: '**/surefire-reports/'

  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Validate Formatting
        run: |
          mvn -B validate -Pformat-check -Denforcer.skip=true
